branch-defaults:
  master:
    environment: proclo-dev
global:
  application_name: proclo
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 running Ruby 2.2 (Puma)
  default_region: null
  profile: null
  sc: git
