branch-defaults:
  rds-in-prod:
    environment: proclo-dev
global:
  application_name: proclo
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: null
  profile: null
  sc: git
