EnvironmentConfigurationMetadata:
  Description: Configuration created from the EB CLI using "eb config save".
  DateCreated: '1446475327000'
  DateModified: '1446475327000'
SolutionStack: 64bit Amazon Linux 2015.03 v2.0.1 running Ruby 2.2 (Puma)
OptionSettings:
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:elb:policies:
    ConnectionDrainingEnabled: true
  aws:elb:healthcheck:
    Interval: '30'
  aws:elasticbeanstalk:application:environment:
    SECRET_KEY_BASE: 4d183b1ce3d7028637b635cc2eb578bfdc89af781ad33532902b843b7366b6a3ef759764f15f9bf3db05dd22df729b680544822793f7b7a8234f4da3895305d5
  aws:elb:loadbalancer:
    CrossZone: true
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t2.micro
  aws:rds:dbinstance:
    DBEngineVersion: 9.4.4
    DBEngine: postgres
    DBUser: ebroot
    DBDeletionPolicy: Snapshot
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateType: Health
    RollingUpdateEnabled: true
EnvironmentTier:
  Type: Standard
  Name: WebServer
Extensions:
  RdsExtensionEB:
    Order: 10000
    SourceLocation: https://s3.amazonaws.com/elasticbeanstalk-env-resources-eu-west-1/eb_snippets/rds/rds.json
AWSConfigurationTemplateVersion: 1.1.0.0
